# Generated by Django 6.0.2 on 2026-03-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '0002_uploadedfile_deleted_at_alter_uploadedfile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvertedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, help_text='Normalized (lowercased, stemmed) token.', max_length=100)),
                ('term_frequency', models.FloatField(help_text='TF = occurrences of this term / total terms in the document.')),
                ('document_frequency', models.IntegerField(default=1, help_text="Number of documents in the owning user's corpus that contain this term.")),
                ('tf_idf', models.FloatField(help_text='Precomputed TF-IDF score at index time.')),
                ('positions', models.JSONField(default=list, help_text='List of token-offset positions (0-based) of this term in the document.')),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(help_text='The source document this term was extracted from.', on_delete=django.db.models.deletion.CASCADE, related_name='index_entries', to='upload.uploadedfile')),
            ],
            options={
                'ordering': ['-tf_idf'],
                'indexes': [models.Index(fields=['term'], name='indexer_inv_term_807fa6_idx'), models.Index(fields=['document'], name='indexer_inv_documen_dc04b3_idx')],
                'unique_together': {('document', 'term')},
            },
        ),
    ]
