# Generated by Django 6.0.2 on 2026-03-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invertedindex',
            name='original_term',
            field=models.CharField(default='', help_text='Original (lowercased, pre-stem) word for human-readable suggestions.', max_length=100),
        ),
    ]
