# Generated by Django 6.0.2 on 2026-03-12 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0002_add_original_term'),
        ('upload', '0003_increase_file_field_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(help_text='A sentence or phrase from the document content.', max_length=200)),
                ('position', models.PositiveIntegerField(default=0, help_text='Sentence order within the document (0-based).')),
                ('document', models.ForeignKey(help_text='The source document this phrase was extracted from.', on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='upload.uploadedfile')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['phrase'], name='indexer_doc_phrase_80c877_idx'), models.Index(fields=['document'], name='indexer_doc_documen_57b862_idx')],
            },
        ),
    ]
