# Generated by Django 6.0.2 on 2026-03-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_uploadedfile_deleted_at_alter_uploadedfile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(max_length=500, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
