# Generated by Django 6.0.2 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_increase_file_field_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(
                choices=[
                    ('pdf', 'PDF'),
                    ('docx', 'Word Document'),
                    ('png', 'PNG Image'),
                    ('jpg', 'JPEG Image'),
                    ('md', 'Markdown'),
                    ('txt', 'Text File'),
                ],
                max_length=10,
            ),
        ),
    ]

